// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises(
    user_id,
    name,
    muscle_group,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, name, muscle_group, notes, created_at, updated_at
`

type CreateExerciseParams struct {
	UserID      *int64 `json:"user_id"`
	Name        string `json:"name"`
	MuscleGroup string `json:"muscle_group"`
	Notes       string `json:"notes"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.UserID,
		arg.Name,
		arg.MuscleGroup,
		arg.Notes,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExercises = `-- name: GetExercises :many
SELECT id, name, muscle_group, notes, created_at, updated_at
FROM exercises
WHERE user_id = $1
`

type GetExercisesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	MuscleGroup string             `json:"muscle_group"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetExercises(ctx context.Context, userID *int64) ([]GetExercisesRow, error) {
	rows, err := q.db.Query(ctx, getExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExercisesRow{}
	for rows.Next() {
		var i GetExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MuscleGroup,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExerciseById = `-- name: UpdateExerciseById :one
UPDATE exercises
SET
    name = COALESCE($1, name),
    muscle_group = COALESCE($2, muscle_group),
    notes = COALESCE($3, notes),
    updated_at = now()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, muscle_group, notes, created_at, updated_at
`

type UpdateExerciseByIdParams struct {
	Name        *string `json:"name"`
	MuscleGroup *string `json:"muscle_group"`
	Notes       *string `json:"notes"`
	ID          int64   `json:"id"`
	UserID      *int64  `json:"user_id"`
}

func (q *Queries) UpdateExerciseById(ctx context.Context, arg UpdateExerciseByIdParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExerciseById,
		arg.Name,
		arg.MuscleGroup,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
