// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises(
    user_id,
    name,
    muscle_group,
    notes
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, name, muscle_group, notes, created_at, updated_at
`

type CreateExerciseParams struct {
	UserID      *int64 `json:"user_id"`
	Name        string `json:"name"`
	MuscleGroup string `json:"muscle_group"`
	Notes       string `json:"notes"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.UserID,
		arg.Name,
		arg.MuscleGroup,
		arg.Notes,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.MuscleGroup,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
