// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID          int64              `json:"id"`
	UserID      *int64             `json:"user_id"`
	Name        string             `json:"name"`
	MuscleGroup string             `json:"muscle_group"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PerformedSet struct {
	ID                int64              `json:"id"`
	WorkoutExerciseID int64              `json:"workout_exercise_id"`
	SetNumber         int32              `json:"set_number"`
	WeightKg          pgtype.Numeric     `json:"weight_kg"`
	Repetitions       int32              `json:"repetitions"`
	Rir               int32              `json:"rir"`
	PerformedAt       pgtype.Timestamptz `json:"performed_at"`
}

type Routine struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoutineExercise struct {
	RoutineID     int64 `json:"routine_id"`
	ExerciseID    int64 `json:"exercise_id"`
	Position      int32 `json:"position"`
	TargetSets    int32 `json:"target_sets"`
	TargetRepsMin int32 `json:"target_reps_min"`
	TargetRepsMax int32 `json:"target_reps_max"`
}

type Session struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        *string            `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserInfo struct {
	UserID      int64          `json:"user_id"`
	Weight      pgtype.Numeric `json:"weight"`
	Avatar      *string        `json:"avatar"`
	DateOfBirth pgtype.Date    `json:"date_of_birth"`
}

type WaterGoal struct {
	UserID       int64              `json:"user_id"`
	GoalAmountMl int32              `json:"goal_amount_ml"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WaterLog struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	AmountMl   int32              `json:"amount_ml"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WorkoutExercise struct {
	ID               int64 `json:"id"`
	WorkoutSessionID int64 `json:"workout_session_id"`
	ExerciseID       int64 `json:"exercise_id"`
	Position         int32 `json:"position"`
}

type WorkoutSession struct {
	ID         int64              `json:"id"`
	RoutineID  *int64             `json:"routine_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Notes      string             `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
