// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
	RevokeSession(ctx context.Context, refreshTokenHash string) (int64, error)
}

var _ Querier = (*Queries)(nil)
