// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetExercises(ctx context.Context, userID *int64) ([]GetExercisesRow, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
	RevokeSession(ctx context.Context, refreshTokenHash string) (int64, error)
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
