// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddExerciseRoutine(ctx context.Context, arg AddExerciseRoutineParams) (int64, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error)
	DeleteExerciseByID(ctx context.Context, arg DeleteExerciseByIDParams) (int64, error)
	DeleteExerciseRoutine(ctx context.Context, arg DeleteExerciseRoutineParams) (int32, error)
	DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) (int64, error)
	GetExerciseRoutine(ctx context.Context, routineID int64) ([]GetExerciseRoutineRow, error)
	GetExercises(ctx context.Context, userID *int64) ([]GetExercisesRow, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
	ListRoutine(ctx context.Context, userID int64) ([]Routine, error)
	ReorderRoutineExercises(ctx context.Context, arg ReorderRoutineExercisesParams) error
	RevokeSession(ctx context.Context, refreshTokenHash string) (int64, error)
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error)
	UpdateExerciseById(ctx context.Context, arg UpdateExerciseByIdParams) (Exercise, error)
	UpdateExerciseRoutine(ctx context.Context, arg UpdateExerciseRoutineParams) (RoutineExercise, error)
	UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error)
}

var _ Querier = (*Queries)(nil)
