// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package db

import (
	"context"
)

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (
    user_id,
    code,
    name,
    description,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    now(),
    now()
)
RETURNING id, user_id, code, name, description, created_at, updated_at
`

type CreateRoutineParams struct {
	UserID      int64  `json:"user_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine,
		arg.UserID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
