// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package db

import (
	"context"
)

const addExerciseRoutine = `-- name: AddExerciseRoutine :execrows
INSERT INTO routine_exercises (
    routine_id,
    exercise_id,
    position,
    target_sets,
    target_reps_min,
    target_reps_max
)
SELECT
    r.id,
    e.id,
    $1,
    $2,
    $3,
    $4
FROM routines r
JOIN exercises e
    ON e.id = $5
WHERE r.id = $6
  AND r.user_id = $7
  AND (
      e.user_id = $7
      OR e.user_id IS NULL
  )
`

type AddExerciseRoutineParams struct {
	Position      int32 `json:"position"`
	TargetSets    int32 `json:"target_sets"`
	TargetRepsMin int32 `json:"target_reps_min"`
	TargetRepsMax int32 `json:"target_reps_max"`
	ExerciseID    int64 `json:"exercise_id"`
	RoutineID     int64 `json:"routine_id"`
	UserID        int64 `json:"user_id"`
}

func (q *Queries) AddExerciseRoutine(ctx context.Context, arg AddExerciseRoutineParams) (int64, error) {
	result, err := q.db.Exec(ctx, addExerciseRoutine,
		arg.Position,
		arg.TargetSets,
		arg.TargetRepsMin,
		arg.TargetRepsMax,
		arg.ExerciseID,
		arg.RoutineID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (
    user_id,
    code,
    name,
    description,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    now(),
    now()
)
RETURNING id, user_id, code, name, description, created_at, updated_at
`

type CreateRoutineParams struct {
	UserID      int64  `json:"user_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine,
		arg.UserID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExerciseRoutine = `-- name: DeleteExerciseRoutine :one
DELETE FROM routine_exercises re
USING routines r
WHERE re.routine_id = $1
  AND re.exercise_id = $2
  AND r.id = re.routine_id
  AND r.user_id = $3
RETURNING re.position
`

type DeleteExerciseRoutineParams struct {
	RoutineID  int64 `json:"routine_id"`
	ExerciseID int64 `json:"exercise_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteExerciseRoutine(ctx context.Context, arg DeleteExerciseRoutineParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteExerciseRoutine, arg.RoutineID, arg.ExerciseID, arg.UserID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const getExerciseRoutine = `-- name: GetExerciseRoutine :many
SELECT
    e.id,
    e.name,
    re.position,
    re.target_sets,
    re.target_reps_min,
    re.target_reps_max
FROM routine_exercises re
INNER JOIN exercises e
    ON e.id = re.exercise_id
WHERE re.routine_id = $1
ORDER BY re.position
`

type GetExerciseRoutineRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Position      int32  `json:"position"`
	TargetSets    int32  `json:"target_sets"`
	TargetRepsMin int32  `json:"target_reps_min"`
	TargetRepsMax int32  `json:"target_reps_max"`
}

func (q *Queries) GetExerciseRoutine(ctx context.Context, routineID int64) ([]GetExerciseRoutineRow, error) {
	rows, err := q.db.Query(ctx, getExerciseRoutine, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExerciseRoutineRow{}
	for rows.Next() {
		var i GetExerciseRoutineRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.TargetSets,
			&i.TargetRepsMin,
			&i.TargetRepsMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutine = `-- name: ListRoutine :many
SELECT id, user_id, code, name, description, created_at, updated_at
FROM routines
WHERE user_id = $1
`

func (q *Queries) ListRoutine(ctx context.Context, userID int64) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutine, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderRoutineExercises = `-- name: ReorderRoutineExercises :exec
UPDATE routine_exercises
SET position = position - 1
WHERE routine_id = $1
  AND position > $2
`

type ReorderRoutineExercisesParams struct {
	RoutineID       int64 `json:"routine_id"`
	DeletedPosition int32 `json:"deleted_position"`
}

func (q *Queries) ReorderRoutineExercises(ctx context.Context, arg ReorderRoutineExercisesParams) error {
	_, err := q.db.Exec(ctx, reorderRoutineExercises, arg.RoutineID, arg.DeletedPosition)
	return err
}
