// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    refresh_token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING user_id, refresh_token_hash, created_at, expires_at
`

type CreateSessionParams struct {
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateSessionRow struct {
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, revoked_at, expires_at
FROM sessions
WHERE refresh_token_hash = $1
`

type GetSessionByRefreshTokenHashRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i GetSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, refreshTokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, refreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :execrows
UPDATE sessions
SET refresh_token_hash = $1
WHERE id = $2
  AND refresh_token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > now()
`

type RotateRefreshTokenParams struct {
	NewRefreshTokenHash string `json:"new_refresh_token_hash"`
	SessionID           int64  `json:"session_id"`
	OldRefreshTokenHash string `json:"old_refresh_token_hash"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshToken, arg.NewRefreshTokenHash, arg.SessionID, arg.OldRefreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
