// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workout.sql

package db

import (
	"context"
)

const createWorkoutSession = `-- name: CreateWorkoutSession :one
INSERT INTO workout_sessions (
    user_id,
    routine_id,
    notes,
    created_at
)
SELECT
    $1,
    r.id,
    $2,
    now()
FROM routines r
WHERE r.id = $3
  AND r.user_id = $1
RETURNING id, user_id, routine_id, started_at, finished_at, notes, created_at
`

type CreateWorkoutSessionParams struct {
	UserID    int64  `json:"user_id"`
	Notes     string `json:"notes"`
	RoutineID int64  `json:"routine_id"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession, arg.UserID, arg.Notes, arg.RoutineID)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoutineID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
